# Generated by Django 3.0.5 on 2020-04-17 14:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KinoCMS', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='date_film',
        ),
        migrations.AddField(
            model_name='news',
            name='date_info',
            field=models.DateField(default=datetime.date.today, verbose_name='Акция стартует'),
        ),
        migrations.AddField(
            model_name='news',
            name='publication',
            field=models.PositiveIntegerField(default=2019, help_text='Публикация'),
        ),
    ]
