# Generated by Django 3.0.5 on 2020-04-17 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('KinoCMS', '0002_auto_20200417_1758'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='cinema',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='KinoCMS.Cinema', verbose_name='Кинотеатр'),
        ),
        migrations.AlterField(
            model_name='news',
            name='publication',
            field=models.PositiveIntegerField(default=2020, help_text='Публикация'),
        ),
    ]
